# Generated by Django 3.1.1 on 2021-11-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Role', models.CharField(max_length=100)),
                ('Job_Desc', models.TextField()),
                ('Place', models.TextField()),
            ],
        ),
    ]
