# Generated by Django 3.1.1 on 2021-11-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='PhoneNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
